document.write("<div id=\"vk_groups\" style = \"position: absolute;top: 120px;right:0px;z-index:50;\">");
document.write("<script src=\"\/scripts\/vk_group.js\"><\/script><\/div>");
document.write("<div id=\"zatemnenie\" style=\"position: absolute;top: 120px; z-index:50;\"><script src=\"\/scripts\/orphus.js\"><\/script>");
document.write("<a href=\"http:\/\/orphus.ru\" id=\"orphus\" target=\"_blank\"><img alt=\"Система Orphus\" src=\"\/images\/orphus.gif\" border=\"0\" width=\"200\" height=\"48\" \/><\/a><\/div>");
document.write("<div style=\"position: absolute;top: 170px; z-index:50;\"><script src=\"\/scripts\/live_internet.js\"><\/script><\/div>");
document.write("<div style=\"position: absolute; top:186px; z-index:50;\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"88\" height=\"31\" style=\"line-height:0;width:88px;\"><tr style=\"height:10px;\">");
document.write("<td style=\"padding:0;width:38px;height:10px;\"><a href=\"http:\/\/www.24log.de\" target=\"_blank\"><img src=\"http:\/\/counter.24log.ru\/buttons\/24\/bg24-7_1.gif\" width=\"38\" height=\"10\" border=\"0\" alt=\"Besucherzahler\" title=\"Besucherzahler \" style=\"margin:0;padding:0;\" \/><\/a><\/td>");
document.write("<td style=\"padding:0;width:50px;height:10px;\"><a href=\"http:\/\/www.24log.ru\" target=\"_blank\"><img src=\"http:\/\/counter.24log.ru\/buttons\/24\/bg24-7_3.gif\" width=\"50\" height=\"10\" border=\"0\" alt=\"\" style=\"margin:0;padding:0;\"><\/a><\/td><\/tr>");
document.write("<tr style=\"height:21px;\"><td style=\"padding:0;width:38px;height:21px\"><a href=\"http:\/\/www.24log.ru\" target=\"_blank\"><img src=\"http:\/\/counter.24log.ru\/buttons\/24\/bg24-7_2.gif\" width=\"38\" height=\"21\" alt=\"счетчик посещений\" title=\"счетчик посещений\" border=\"0\" style=\"margin:0;padding:0;\" \/><\/a><\/td>");
document.write("<script src=\"\/scripts\/24log_statistic.js\"><\/script><\/tr><\/table><\/div>");
document.write("<span id=\"openstat1\"><\/span>");
document.write("<div style=\"position: absolute; top:170px; left:112px; z-index:50;\">");
document.write("<span id=\"openstat2376513\"><\/span>");
document.write("<script src=\"\/scripts\/open_stat.js\"><\/script><\/div>");
document.write("<script src=\"\/scripts\/mail_ru_statistic.js\"><\/script>");
document.write("<div style=\"position: absolute; top:186px; left:112px; z-index:50;\">");
document.write("<a href=\"http:\/\/top.mail.ru\/jump?from=2687907\">");
document.write("<img src=\"\/\/top-fwz1.mail.ru\/counter?id=2687907;t=479;l=1\" ");
document.write("style=\"border:0;\" height=\"31\" width=\"88\" alt=\"Рейтинг@Mail.ru\" \/><\/a><\/div>");
document.write("<div style=\"position: absolute; top:217px; z-index:50; cursor:url(\/cursors\/cursor2.cur), progress !important;\"><\/div>");