document.write("<div class = \"cursor\" style = \"position:fixed;width:100%;height:100%;\"><\/div>");
document.write("<div id = \"rectangle\"><font color=\"white\" class = \"bebas\"><center><div style = \"position: relative; z-index=1;\">Free Games Studio<\/div><\/center><\/font><\/div>");
document.write("<table id=\"nav8\" cellspacing=\"0\"><tr>");
document.write("<td><a href=\"http:\/\/fgs.pp.ua\/\"><font face=\"Helvetica\">Главная<\/font><\/a><\/td>");
document.write("<td class=\"right\"><a href=\"/news\"><font face=\"Helvetica\">Новости<\/font><\/a><\/td>");
document.write("<td><a href=\"http:\/\/fgs.pp.ua\/games\/\"><font face=\"Helvetica\">Игры<\/a><ul>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-ОПЕРАЦИОННЫЕ СИСТЕМЫ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/games\/Windows\"><font face=\"Helvetica\"><center>Для ОS Windows<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/games\/Ubuntu\"><font face=\"Helvetica\"><center>Для ОS Ubuntu (Linux)<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/games\/Mac ОS X\"><font face=\"Helvetica\"><center>Для Mac ОS X<\/center><\/font><\/a><\/li>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-МОБИЛЬНЫЕ ПЛАТФОРМЫ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/games\/Android\"><font face=\"Helvetica\"><center>Для ОS Android<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/games\/iOS\"><font face=\"Helvetica\"><center>Для iOS<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/games\/Tizen\"><font face=\"Helvetica\"><center>Для ОS Tizen<\/center><\/font><\/a><\/li>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-КОНСОЛИ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/games\/Xbox One\"><font face=\"Helvetica\"><center>Для Xbox One<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/games\/PlayStation 4\"><font face=\"Helvetica\"><center>Для PlayStation 4<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/games\/PlayStation Vita\"><font face=\"Helvetica\"><center>Для PlayStation Vita<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/games\/PlayStation 3\"><font face=\"Helvetica\"><center>Для PlayStation 3<\/center><\/font><\/a><\/li>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-ДРУГОЕ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/games\/Online\"><font face=\"Helvetica\"><center>Онлайн<\/center><\/font><\/a><\/li>");
document.write("<\/ul><\/td>");
document.write("<td><a href=\"http:\/\/fgs.pp.ua\/apps\/\"><font face=\"Helvetica\">Программы<\/font><\/a><ul>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-ОПЕРАЦИОННЫЕ СИСТЕМЫ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/apps\/Windows\"><font face=\"Helvetica\"><center>Для ОS Windows<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/apps\/Ubuntu\"><font face=\"Helvetica\"><center>Для ОS Ubuntu (Linux)<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/apps\/Mac ОS X\"><font face=\"Helvetica\"><center>Для Mac ОS X<\/center><\/font><\/a><\/li>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-МОБИЛЬНЫЕ ПЛАТФОРМЫ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/apps\/Android\"><font face=\"Helvetica\"><center>Для ОS Android<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/apps\/iOS\"><font face=\"Helvetica\"><center>Для iOS<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/apps\/Tizen\"><font face=\"Helvetica\"><center>Для ОS Tizen<\/center><\/font><\/a><\/li>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-КОНСОЛИ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/apps\/Xbox One\"><font face=\"Helvetica\"><center>Для Xbox One<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/apps\/PlayStation 4\"><font face=\"Helvetica\"><center>Для PlayStation 4<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/apps\/PlayStation Vita\"><font face=\"Helvetica\"><center>Для PlayStation Vita<\/center><\/font><\/a><\/li>");
document.write("<li><a href=\"\/apps\/PlayStation 3\"><font face=\"Helvetica\"><center>Для PlayStation 3<\/center><\/font><\/a><\/li>");
document.write("<center><font face=\"Arial\" color = \"white\"><optgroup label=\"-ДРУГОЕ-\"><\/optgroup><\/font><\/center>");
document.write("<li><a href=\"\/apps\/Online\"><font face=\"Helvetica\"><center>Онлайн<\/center><\/font><\/a><\/li>");
document.write("<\/ul><\/td>");
document.write("<td class=\"right\"><a href=\"/about_us\"><font face=\"Helvetica\">О нас<\/font><\/a><\/td>");
document.write("<td class=\"right\"><a href=\"/in_developing\"><font face=\"Helvetica\">В разработке<\/font><\/a><\/td>");
document.write("<td class=\"right\"><a href=\"/support_us\"><font face=\"Helvetica\">Поддержать нас<\/font><\/a><\/td>");
document.write("<\/tr><\/table>");